# yaml 配置实例
version: '3'
services:
  web:
    image: blackie/nginx-auth-digest:latest
    ports:
      - "9999:80"
    volumes:
      - /Users/ct.tsai/Desktop/Repo/github/nginx-simple-auth/nginx/config/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - /Users/ct.tsai/Desktop/Repo/github/nginx-simple-auth/nginx/html:/usr/local/nginx/html
      - /Users/ct.tsai/Desktop/Repo/github/nginx-simple-auth/nginx/auth:/usr/local/nginx/auth
      - /Users/ct.tsai/Desktop/Repo/github/nginx-simple-auth/nginx/logs:/usr/local/nginx/logs